- app/components/chat.tsx
- app/store/mask.ts
> fix(15): 修复插件功能支持模型判断逻辑

- package.json
- yarn.lock
详情见： langchain-ai/langchainjs#2078
> 🐛  修复 azure openai 新接口版本报错的问题

- app/api/langchain-tools/dalle_image_generator.ts
> fix(43): fix dall-e plugin

- README.md
- app/api/langchain-tools/arxiv.ts
- app/api/langchain/tool/agent/route.ts
- app/plugins/cn.ts
- app/plugins/en.ts
- yarn.lock
https://github.com/Hk-Gosuto/ChatGPT-Next-Web-LangChain/issues/51
> feat: add arxiv plugin

- app/client/api.ts
- app/client/platforms/openai.ts
- app/components/chat.module.scss
- app/components/chat.tsx
- app/components/markdown.tsx
- app/constant.ts
- app/store/chat.ts
- app/styles/markdown.scss
> feat support visual model

- app/components/chat.tsx
- app/components/emoji.tsx
- app/components/plugin.tsx
七牛云的cdn好像又出问题了15.0.1也很多不能显示，测试了下`https://cdnjs.cloudflare.com`正常显示
> fix: cdn emoji links

- app/layout.tsx
昨天的提交的 PR 忘记修改 layout 中的 meta themeColor，导致刷新的时候会一瞬间显示原来的 themeColor
> chore: update layout metadata themeColor

- app/components/chat.tsx
Add loading animation
Upload error message
> feat: optimize upload

- app/components/home.module.scss
- app/components/plugin.module.scss
- app/components/search-bar.tsx
- app/locales/cn.ts
- app/locales/en.ts
* chore: add placeholder on sidebar search
* chore: modify input:focus border-color to adapting to global theme
> fix: sidebar search :focus border on Safari

- app/masks/en.ts
Added a mask mainly translation of jailbreak chinese version to english version
> Added an mask [en.ts]

- app/masks/en.ts
> 更新一下mask配置，之前新加的配置多了一个id导致构建失败

- README.md
- app/api/langchain-tools/edge_tools.ts
- app/api/langchain-tools/myfiles_browser.ts
- app/api/langchain-tools/nodejs_tools.ts
- app/api/langchain-tools/pdf_browser.ts
- app/api/langchain/rag/search/route.ts
- app/api/langchain/rag/store/route.ts
- app/api/langchain/tool/agent/agentapi.ts
- app/api/langchain/tool/agent/edge/route.ts
- app/api/langchain/tool/agent/nodejs/route.ts
- app/client/api.ts
- app/client/platforms/anthropic.ts
- app/client/platforms/openai.ts
- app/components/chat.tsx
- app/store/chat.ts
- app/utils.ts
- next.config.mjs
- package.json
- yarn.lock
Feat: claude model function call support
> Feat claude function call

- next.config.mjs
> fix: vercel 504 error

- app/api/langchain/tool/agent/agentapi.ts
- next.config.mjs
- package.json
> Fix vercel 504 error

- app/components/search-bar.tsx
fix: search special character error
> fix: search special character error

- app/api/langchain-tools/pdf_browser.ts
- [x ] fix    
- [ x] perf    
1. Modify tool calling description into ['url','instructions','keyword for searching']
2. Modify prompts for pdf reading
3. Add page limit (20 default)
> PDF plugin improvement

- README.md
- app/api/config/route.ts
- app/client/platforms/openai.ts
- app/config/server.ts
- app/store/access.ts
> feat: remote model

- app/api/langchain-tools/arxiv.ts
1. Replace raw xml input to parsed data
2. Modify prompts and default values of zod request
> Modify ArxivAPIWrapper

- README.md
- app/api/[provider]/[...path]/route.ts
- app/api/auth.ts
- app/api/deepseek.ts
- app/api/siliconflow.ts
- app/client/api.ts
- app/client/platforms/deepseek.ts
- app/client/platforms/siliconflow.ts
- app/components/settings.tsx
- app/config/server.ts
- app/constant.ts
- app/locales/cn.ts
- app/locales/en.ts
- app/store/access.ts
- app/utils.ts
- app/utils/chat.ts
- app/utils/model.ts
> feat: sync deepseek r1 thinking code

- app/constant.ts
- app/utils.ts
> Feat google model update

- app/constant.ts
- app/utils.ts
> feat: gpt 4.5 support

- app/components/button.module.scss
- app/components/button.tsx
- app/components/chat.module.scss
- app/components/chat.tsx
- app/icons/voice-close.svg
- app/icons/voice-open.svg
- app/locales/cn.ts
- app/locales/en.ts
> feat: stt style optimize

- app/constant.ts
- app/utils.ts
add o1-pro
support gpt-4.1 vision
> feat: support gpt-4.1 vision

- app/constant.ts
- app/utils.ts
Add support for new Gemini 2.5 preview models
> feat: Add support for new Gemini 2.5 preview models

- app/api/config/route.ts
- app/components/chat.tsx
- app/config/server.ts
- app/constant.ts
- app/store/access.ts
- app/utils.ts
feat: update vision model filter
> feat: update vision model filter
